#!/bin/bash

# Path to your virtual environment
VENV_DIR="/opt/penterep-tools/penterep-tools"

# Check if the virtual environment is already activated
if [ -z "$VIRTUAL_ENV" ]; then
    echo "Activating virtual environment..."
    source "$VENV_DIR/bin/activate"
    if [ -z "$VIRTUAL_ENV" ]; then
        echo "Failed to activate virtual environment."
        exit 1
    else
        echo "Virtual environment activated."
    fi
else
    echo "Virtual environment is already activated."
fi

# Keep the virtual environment active in the current shell
exec "$SHELL"