#!/usr/bin/env python3
import os
import venv
import sys

def create_virtual_environment(venv_dir):
    """Create a virtual environment at the specified directory."""
    print(f"Creating virtual environment in {venv_dir}...")
    venv.EnvBuilder(with_pip=True).create(venv_dir)
    print("Virtual environment created successfully.")


VENV_DIR = os.path.join("/opt", "penterep-tools", "penterep-tools")

try:
    if not os.path.exists(VENV_DIR):
        create_virtual_environment(VENV_DIR)
    else:
        print(f"Virtual environment already exists in {VENV_DIR}.")
        sys.exit(0)

    sys.exit(0)

except Exception as e:
    print(f"Error creating virtual environment: {e}")
    sys.exit(1)