#!/bin/bash
set -e

# Color definitions
RED='\033[0;31m'
ORANGE='\033[38;5;214m'
NC='\033[0m' # (color reset)

# Define cleanup function
cleanup() {
    echo -e "${RED}[!] Installation failed, purging directory /opt/penterep-tools...${NC}"
    rm -rf /opt/penterep-tools
}
# Set trap to call cleanup on exit if the script fails
trap 'cleanup' ERR

# Paths to relevant scripts
PT_VENV_SCRIPT="/opt/penterep-tools/helpers/ptvenv"
VENV_ACTIVATE="/opt/penterep-tools/penterep-tools/bin/activate"

# Get the full Python version
FULL_PYTHON_VERSION=$(python --version | awk '{print $2}')

# Extract the major and minor version
if [[ "$FULL_PYTHON_VERSION" =~ ^[0-9]+\.[0-9]+ ]]; then
    PYTHON_VERSION=$(echo "$FULL_PYTHON_VERSION" | cut -d. -f1,2)
else
    echo -e "${RED}[!] Failed to determine Python version.${NC}"
    exit 1
fi

# Run the script for creating the virtual environment
if command -v "$PT_VENV_SCRIPT"; then
    echo -e "${ORANGE}[+] Running script for creating venv:${NC} $PT_VENV_SCRIPT"
    "$PT_VENV_SCRIPT"
    echo -e "${ORANGE}[+] Venv created successfully.${NC}"
else
    echo -e "${RED}[!] Script $PT_VENV_SCRIPT was not found.${NC}"
    exit 1
fi

# Activate the virtual environment
echo -e "${ORANGE}[+] Activating virtual environment...${NC}"
if [ -f "$VENV_ACTIVATE" ]; then
    source "$VENV_ACTIVATE"

    # Install ptmanager
    echo -e "${ORANGE}[+] Installing ptmanager...${NC}"
    pip install --quiet ptmanager || { echo -e "${RED}Installation failed.${NC}"; exit 1; }
else
    echo -e "${RED}[!] The file to activate the virtual environment was not found.${NC}"
    exit 1
fi

# Ask about installing other tools
while true; do
    read -p "[+] Would you like to install other penterep tools as well? (Y/n): " choice
    choice=${choice:-Y}
    case "$choice" in
        [Yy]* )
            echo -e "${ORANGE}[+] Installing all penterep tools...${NC}"
            source "$VENV_ACTIVATE" && python3 "/opt/penterep-tools/penterep-tools/lib/python${PYTHON_VERSION}/site-packages/ptmanager/ptmanager.py" --tools-install > /dev/null 2>&1 || {
                echo -e "${RED}[!] Installation of additional tools failed.${NC}"
                exit 1
            }
            echo -e "${ORANGE}[+] Penterep tools successfully installed.${NC}"
            break;;
        [Nn]* )
            echo -e "${ORANGE}[+] Installation of other penterep tools was skipped.${NC}"
            break;;
        * )
            echo -e "${RED}[*] Please enter 'y' for yes or 'n' for no.${NC}";;
    esac
done


#REGISTER_TOOLS_SCRIPT="/opt/penterep-tools/helpers/register-tools"
REGISTER_TOOLS_SCRIPT="/usr/local/bin/register-tools"
# Call register-tools to register ptmanager and other tools
#echo -e "${ORANGE}[+] Registering tools...${NC}"
"$REGISTER_TOOLS_SCRIPT" || { echo -e "${RED}[!] Registration of tools failed.${NC}"; exit 1; }

echo -e "${ORANGE}[+] Installation successful.${NC}"
exit 0
