#!/bin/bash
set -e

# Výpis loga
echo "
 ____            _                        _____           _
|  _ \ ___ _ __ | |_ ___ _ __ ___ _ __   |_   _|__   ___ | |___
| |_) / _ \ '_ \| __/ _ \ '__/ _ \ '_ \    | |/ _ \ / _ \| / __|
|  __/  __/ | | | ||  __/ | |  __/ |_) |   | | (_) | (_) | \__ \\
|_|   \___|_| |_|\__\___|_|  \___| .__/    |_|\___/ \___/|_|___/
                                 |_|

Starting uninstallation process...
"

# Check if in a virtual environment
if [ -n "$VIRTUAL_ENV" ]; then
    # Deactivate the virtual environment
    deactivate || echo "Not in a virtual environment or failed to deactivate."
fi

# Remove the directory /opt/penterep-tools if it exists
if [ -d "/opt/penterep-tools" ]; then
    echo "Deleting folder /opt/penterep-tools..."
    rm -rf /opt/penterep-tools
else
    echo "Folder /opt/penterep-tools does not exist."
fi

exit 0
