#!/bin/bash
set -e

C='\033[38;5;214m'
NC='\033[0m' # (color reset)

case "${1:-}" in
    remove)
        # A real uninstall is the only operation that should be presented as
        # an uninstallation. dpkg also calls prerm during upgrades.
        echo "
 ____            _                        _____           _
|  _ \ ___ _ __ | |_ ___ _ __ ___ _ __   |_   _|__   ___ | |___
| |_) / _ \ '_ \| __/ _ \ '__/ _ \ '_ \    | |/ _ \ / _ \| / __|
|  __/  __/ | | | ||  __/ | |  __/ |_) |   | | (_) | (_) | \__ \\
|_|   \___|_| |_|\__\___|_|  \___| .__/    |_|\___/ \___/|_|___/
                                 |_|
"

        echo -e "${C}[+] Starting uninstallation process...${NC}"
        ;;

    upgrade)
        # Keep package upgrades quiet; installation progress is shown by the
        # new package's preinst/postinst scripts.
        ;;
esac

exit 0
